<a href="https://colab.research.google.com/github/vishal-05/Dr-Mac/blob/main/Nutriv.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Nutriv Project

In [ ]:
import numpy as np
import pandas as pd

## Importing the dataset

In [ ]:
recipes = pd.read_csv('epi_r.csv')
X = recipes.iloc[:, 2:].values
y = recipes.iloc[:, 0].values

In [ ]:
print(X)

[[4.260e+02 3.000e+01 7.000e+00 ... 0.000e+00 0.000e+00 1.000e+00]
 [4.030e+02 1.800e+01 2.300e+01 ... 0.000e+00 0.000e+00 0.000e+00]
 [1.650e+02 6.000e+00 7.000e+00 ... 0.000e+00 0.000e+00 0.000e+00]
 ...
 [1.990e+02 3.000e+00 2.100e+01 ... 0.000e+00 0.000e+00 0.000e+00]
 [1.466e+03 1.200e+01 1.000e+02 ... 0.000e+00 0.000e+00 0.000e+00]
 [2.470e+02 1.000e+00 2.600e+01 ...       nan       nan       nan]]


In [ ]:
print(y)

['Lentil, Apple, and Turkey Wrap '
 'Boudin Blanc Terrine with Red Onion Confit '
 'Potato and Fennel Soup Hodge ' ... 'Almond Brown Butter '
 'Spiced Chocolate Torte Wrapped in Chocolate Ribbons ' 'Herbed Olives ']


## Filtering based on Calories and Type of food

In [ ]:
def filter_by_cal(df, min_calories, max_calories):
    return df[(df['calories'] >= min_calories) & (df['calories'] <= max_calories) & (df['breakfast'] >= 1)]

filter_C =filter_by_cal(recipes, 400, 600)
recommended_recipe = filter_C.sample(n=2)

# Step 5: Print out the recommended recipes
print(recommended_recipe.loc[:, 'title':'breakfast'])

                                         title  rating  calories  protein  \
15282  Sausage and Potato Breakfast Casserole    4.375     421.0     21.0   
13216                   Spiced Nectarine Cake    4.375     499.0      9.0   

        fat  sodium  #cakeweek  #wasteless  22-minute meals  \
15282  29.0   743.0          0           0                0   
13216  14.0   253.0          0           0                0   

       3-ingredient recipes  ...  bon appétit  bon app��tit  boston  bourbon  \
15282                     0  ...            1             0       0        0   
13216                     0  ...            1             0       0        0   

       braise  bran  brandy  bread  breadcrumbs  breakfast  
15282       0     0       0      0            0          1  
13216       0     0       0      0            0          1  

[2 rows x 73 columns]


In [ ]:
print('vishesh')

vishesh


In [ ]:
print('vishal')

vishal


In [14]:
#@title lunch selector
repes = pd.read_csv('Nutriv.csv')


In [21]:
def filter_by_cal_lunch(df, min_calories, max_calories):
    return df[(df['calories'] >= min_calories) & (df['calories'] <= max_calories) & (df['lunch'] >= 1)]

filter_C =filter_by_cal_lunch(recipes, 400, 600)
recommended_recipe = filter_C.sample(n=2)
recommended_recipe = recommended_recipe[['title','calories','protein','fat', 'lunch']]
# Step 5: Print out the recommended recipes
print(recommended_recipe)

                                                   title  calories  protein  \
12238  Onions Filled with Hashed-Brown Potatoes and B...     442.0     12.0   
4962                 Ripe Olive and Avocado Quesadillas      415.0     13.0   

        fat  lunch  
12238  18.0    1.0  
4962   26.0    1.0  


In [22]:
def filter_by_cal_dinner(df, min_calories, max_calories):
    return df[(df['calories'] >= min_calories) & (df['calories'] <= max_calories) & (df['lunch'] >= 1)]

filter_C =filter_by_cal_dinner(recipes, 400, 600)
recommended_recipe = filter_C.sample(n=2)
recommended_recipe = recommended_recipe[['title','calories','protein','fat', 'dinner']]
# Step 5: Print out the recommended recipes
print(recommended_recipe)

                                                 title  calories  protein  \
18755               Curried Ground Shrimp and Noodles      575.0     35.0   
558    Cold Poached Chicken with Chinese Garlic Sauce      442.0     37.0   

        fat  dinner  
18755  11.0     1.0  
558    21.0     0.0  
